import type { MobileAnnotation } from "./schemas/mobile-annotation";
import type { Session } from "./schemas/session";

export interface ExportData {
	session?: Session;
	annotations: MobileAnnotation[];
	exportedAt: string;
}

export function exportToJson(annotations: MobileAnnotation[], session?: Session): string {
	const data: ExportData = {
		session,
		annotations,
		exportedAt: new Date().toISOString(),
	};
	return JSON.stringify(data, null, 2);
}

export function exportToMarkdown(annotations: MobileAnnotation[], session?: Session): string {
	const lines: string[] = [];

	if (session) {
		lines.push(`# Annotations Report - ${session.name}`);
		lines.push("");
		lines.push(`**Device:** ${session.deviceId} | **Platform:** ${session.platform}`);
		lines.push(`**Date:** ${session.createdAt}`);
	} else {
		lines.push("# Annotations Report");
	}

	lines.push("");
	lines.push(`**Total annotations:** ${annotations.length}`);
	lines.push("");
	lines.push("---");

	for (let i = 0; i < annotations.length; i++) {
		const annotation = annotations[i];
		lines.push("");
		lines.push(`## Annotation #${i + 1}: ${annotation.comment}`);
		lines.push("");
		lines.push(`- **Status:** ${annotation.status}`);
		lines.push(`- **Intent:** ${annotation.intent} | **Severity:** ${annotation.severity}`);
		lines.push(`- **Position:** ${annotation.x}%, ${annotation.y}%`);

		if (annotation.element) {
			lines.push(
				`- **Element:** ${annotation.element.componentName} (${annotation.element.componentPath})`,
			);
		}

		lines.push(`- **Created:** ${annotation.createdAt}`);

		if (annotation.thread.length > 0) {
			lines.push("");
			lines.push("### Thread");
			lines.push("");
			for (const message of annotation.thread) {
				lines.push(`> **${message.role}** (${message.timestamp}): ${message.content}`);
				lines.push("");
			}
		}
	}

	return lines.join("\n");
}

export function formatGitHubIssueBody(annotation: MobileAnnotation, session?: Session): string {
	const lines: string[] = [];

	lines.push("## Annotation Details");
	lines.push("");
	lines.push(`**Comment:** ${annotation.comment}`);
	lines.push(`**Intent:** ${annotation.intent} | **Severity:** ${annotation.severity}`);
	lines.push(`**Status:** ${annotation.status}`);
	lines.push("");

	lines.push("## Context");
	lines.push("");
	lines.push(`- **Position:** ${annotation.x}%, ${annotation.y}%`);
	lines.push(`- **Screen:** ${annotation.screenWidth}x${annotation.screenHeight}`);
	lines.push(`- **Device:** ${annotation.deviceId}`);
	lines.push(`- **Platform:** ${annotation.platform}`);

	if (session) {
		lines.push(`- **Session:** ${session.name} (${session.id})`);
	}

	if (annotation.element) {
		lines.push("");
		lines.push("## Element");
		lines.push("");
		lines.push(`- **Component:** ${annotation.element.componentName}`);
		lines.push(`- **Path:** ${annotation.element.componentPath}`);
		if (annotation.element.componentFile) {
			lines.push(`- **File:** ${annotation.element.componentFile}`);
		}
		if (annotation.element.textContent) {
			lines.push(`- **Text:** ${annotation.element.textContent}`);
		}
		if (annotation.element.accessibility) {
			const a11y = annotation.element.accessibility;
			if (a11y.label) lines.push(`- **Accessibility label:** ${a11y.label}`);
			if (a11y.role) lines.push(`- **Accessibility role:** ${a11y.role}`);
		}
	}

	if (annotation.thread.length > 0) {
		lines.push("");
		lines.push("## Thread");
		lines.push("");
		for (const message of annotation.thread) {
			lines.push(`> **${message.role}** (${message.timestamp}): ${message.content}`);
			lines.push("");
		}
	}

	lines.push("");
	lines.push("---");
	lines.push(`*Generated by agentation-mobile on ${new Date().toISOString()}*`);

	return lines.join("\n");
}
